vipa_citation_new:
    path:     /{journalId}/article/{articleId}/advanced-citation/new
    defaults: { _controller: "VipaCitationBundle:Citation:new" }

vipa_citation_create:
    path:     /{journalId}/article/{articleId}/advanced-citation/create
    defaults: { _controller: "VipaCitationBundle:Citation:create" }
    methods:  [POST]

vipa_citation_edit:
    path:     /{journalId}/article/{articleId}/advanced-citation/{id}/edit
    defaults: { _controller: "VipaCitationBundle:Citation:edit" }

vipa_citation_update:
    path:     /{journalId}/article/{articleId}/advanced-citation/{id}/update
    defaults: { _controller: "VipaCitationBundle:Citation:update" }
    methods:  [PUT]

vipa_citation_rest_parse:
    path:     /citations-to-form/
    defaults: { _controller: "VipaCitationBundle:Citation:citationsToForm" }
    methods:  [POST]


vipa_citation_freecite_parse:
    path:     /citations-freecite-parse/
    defaults: { _controller: "VipaCitationBundle:ExtraCitation:parse" }
    methods:  [POST]
