services:
  extra_citation.extra_citation_subscriber:
        class: Vipa\CitationBundle\EventListener\ExtraCitationEventSubscriber
        arguments: ["@router", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }
  advanced_citation.citation_subscriber:
      class: Vipa\CitationBundle\EventListener\CitationEventSubscriber
      arguments: ["@router", "@doctrine.orm.entity_manager"]
      tags:
          - { name: kernel.event_subscriber }
  advanced_citation.twig_subscriber:
      class: Vipa\CitationBundle\EventListener\TwigEventSubscriber
      arguments: ["@doctrine.orm.entity_manager", "@twig", "%kernel.root_dir%"]
      tags:
          - { name: kernel.event_subscriber }
